#!/usr/bin/env python3
"""results/summary.md from results/run.json.   python scripts/summarize.py [results]"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results")
out = []


def P(s=""):
    out.append(s)


def table(cols, rows):
    P("| " + " | ".join(cols) + " |"); P("|" + "---|" * len(cols))
    for r in rows:
        P("| " + " | ".join(str(c) for c in r) + " |")
    P()


def f(x, d=2):
    return "-" if x is None else f"{x:,.{d}f}"


def pct(x, d=1):
    return "-" if x is None else f"{100 * x:.{d}f} %"


run = json.load(open(os.path.join(R, "run.json"), encoding="utf-8"))
P("# Results summary\n")
P("Generated by scripts/summarize.py from results/run.json.\n")
t = run.get("tape", {})
P(f"## The tape\n")
P(f"{t.get('tape_hours_span', 0):.1f} hours of Deribit BTC options recorded from {t.get('from')} to {t.get('to')}: {t.get('ticker_rows', 0):,} ticker updates on {t.get('instruments', 0)} options, {t.get('prints', 0):,} prints, {t.get('index_rows', 0):,} index prints; the recorder (tools/record.py) keeps running and every number below is recomputed on a longer tape by `python -m optmm run`.\n")

m = run.get("mm", {}); runs = m.get("runs", {}); c = m.get("comparison", {})
if runs:
    P("## The one number: the quoters on the recorded tape\n")
    a, s_, mk = runs.get("aware", {}), runs.get("surface", {}), runs.get("market", {})
    P(f"Over {c.get('hours', 0):.1f} hours, quoting every option within 25 % of the index on the two dailies, the weekly, the monthly and the quarterly at the screen's own half-spread: the market-mark quoter filled {mk.get('fills', 0)} times for {f(mk.get('pnl_usd'), 0)} USD, the surface quoter {s_.get('fills', 0)} times for {f(s_.get('pnl_usd'), 0)} USD, the inventory-aware surface quoter {a.get('fills', 0)} times for {f(a.get('pnl_usd'), 0)} USD "
      f"({f(a.get('pnl_per_contract_usd'), 1)} USD per contract against {f(mk.get('pnl_per_contract_usd'), 1)} for the market-mark quoter). Spread capture at the print: market {f(mk.get('spread_capture_usd'), 0)}, surface {f(s_.get('spread_capture_usd'), 0)}, aware {f(a.get('spread_capture_usd'), 0)} USD; delta-hedged 5-minute mark-out beyond the spread (adverse selection): {f(mk.get('adverse_selection_5m_usd'), 0)}, {f(s_.get('adverse_selection_5m_usd'), 0)}, {f(a.get('adverse_selection_5m_usd'), 0)} USD; fees {f(mk.get('fees_usd'), 0)}, {f(s_.get('fees_usd'), 0)}, {f(a.get('fees_usd'), 0)} USD; the largest vega carried {f(mk.get('max_abs_vega'), 0)}, {f(s_.get('max_abs_vega'), 0)}, {f(a.get('max_abs_vega'), 0)} USD per vol point.\n")
    table(["quoter", "fills", "contracts", "P&L (USD)", "per contract", "spread capture", "mark-out 1m", "mark-out 5m", "hedged mark-out 5m", "mark-out 30m", "fees", "hedge P&L", "hedges", "pulls", "max |vega|", "max |delta| (BTC)", "quotes live"],
          [[k, v["fills"], f(v["contracts"], 1), f(v["pnl_usd"], 0), f(v["pnl_per_contract_usd"], 1), f(v["spread_capture_usd"], 0), f(v["markout_1m_usd"], 0), f(v["markout_5m_usd"], 0), f(v.get("markout_dh_5m_usd"), 0), f(v["markout_30m_usd"], 0), f(v["fees_usd"], 0), f(v["hedge_pnl_usd"], 0), v["n_hedges"], v.get("n_pulls", 0), f(v["max_abs_vega"], 0), f(v["max_abs_delta_btc"], 2), f(v["avg_quotes"], 0)] for k, v in runs.items()])
    P("Mark-outs are the change in Deribit's mark from the fill price in the direction of the position (positive = the mark moved in our favour); the hedged mark-out removes the delta times the index move, which the perpetual hedge carries; adverse selection is the hedged 5-minute mark-out beyond the spread captured at the print. Fees are Deribit's 0.0003 BTC per option contract capped at 12.5 % of the premium and 0.035 % taker on the perpetual hedge. All three quoters post the same size at the same half-spread under the same protections (re-pricing off the live index, the fast-market pull, the hard vega limit) and differ only in where they centre the quote and whether the inventory leans it. `aware_slow` re-prices on the 5-second timer only; `aware_noprot` and `market_noprot` run without any protection.\n")

ts = run.get("tape_surfaces", {})
if ts.get("n_surfaces"):
    P("## Surfaces on the tape\n")
    P(f"{ts['n_surfaces']} surfaces (one every {ts['step_s']} s, {ts['n_slices']} slices, {ts['quotes_per_surface']:.0f} two-sided quotes each): RMSE {ts['rmse_vol_points_median']:.2f} vol points (median; mean {ts['rmse_vol_points_mean']:.2f}), median max error {ts['max_err_vol_points_median']:.2f}, {ts['butterfly_violations_total']} butterfly violations, calendar-arbitrage-free in {pct(ts['calendar_ok_share'])} of surfaces, the fitted fair inside the screen's bid-ask for {pct(ts['within_spread_share_mean'])} of quotes, median distance to Deribit's own mark IV {ts['mark_iv_abs_diff_volpts_median']:.2f} vol points. Expiries on the tape: {', '.join(str(x) for x in ts['expiries_days'])} days.\n")
    table(["expiry (days)", "ATM vol", "25-delta RR (put - call)"], [[k, pct(v, 1), pct(ts['rr25_by_expiry'].get(k), 1)] for k, v in ts["atm_vol_by_expiry"].items()])

hs = run.get("history_surfaces", {})
if hs.get("n_slices"):
    P("## Surfaces from the trade history\n")
    P(f"{hs['n_slices']:,} SSVI slices on {hs['n_days']:,} days ({hs['months'][0]} to {hs['months'][1]}, {hs['trades_used']:,} prints in the two hours before the 08:00 UTC settlement): RMSE {hs['rmse_vol_points_median']:.2f} vol points (median; mean {hs['rmse_vol_points_mean']:.2f}), {hs['butterfly_violations']} butterfly violations, calendar-arbitrage-free on {pct(hs['calendar_ok_share'])} of days. ATM vol percentiles p5/p50/p95: {pct(hs['atm_vol_percentiles']['p5'], 0)} / {pct(hs['atm_vol_percentiles']['p50'], 0)} / {pct(hs['atm_vol_percentiles']['p95'], 0)}; 25-delta RR p5/p50/p95: {pct(hs['rr25_percentiles']['p5'], 1)} / {pct(hs['rr25_percentiles']['p50'], 1)} / {pct(hs['rr25_percentiles']['p95'], 1)}.\n")
    table(["year", "days", "RMSE (vol points)", "calendar-free days"], [[y, v["days"], f(v["rmse_vol_points"], 2), pct(v["calendar_ok_share"])] for y, v in hs["by_year"].items()])

ch = run.get("chains", {})
if any(isinstance(v, dict) for v in ch.values()):
    P("## Listed-equity surfaces from the end-of-day chains\n")
    table(["symbol", "days", "slices", "quotes", "RMSE (vol pts, median)", "max error (median)", "model inside bid-ask", "RMSE in half-spreads", "butterfly violations", "calendar-free days", "vs vendor IV (vol pts)", "ATM vol front (median)", "RR25 front (median)"],
          [[k, v["days_fitted"], v["slices"], f"{v['quotes']:,}", f(v["rmse_vol_points_median"], 2), f(v["max_err_vol_points_median"], 2), pct(v["within_spread_share_mean"]), f(v["rmse_half_spreads_median"], 1), v["butterfly_violations"], pct(v["calendar_ok_share"]), f(v["vendor_iv_abs_diff_volpts_median"], 2), pct(v["atm_vol_front_median"], 1), pct(v["rr25_front_median"], 1)] for k, v in ch.items() if isinstance(v, dict)])

mi = run.get("micro", {})
if mi:
    P("## Microstructure of quoting\n")
    pk = mi.get("pickoff", {})
    if pk.get("pairs"):
        P(f"Pick-off: {pk['events']} index moves of at least {pk['threshold_bp']:.0f} bp within {pk['window_s']} s; over {pk['pairs']:,} option-event pairs within 15 % of the money the best quote changed after a median {pk['median_latency_s']:.1f} s, {pct(pk['share_stale_5s'])} were still unchanged after 5 s and {pct(pk['share_stale_30s'])} after 30 s; the move exceeded the half-spread for {pct(pk['share_move_exceeds_half_spread'])} of pairs, and a quote left at the old level would have given up {f(pk['mean_pickoff_loss_usd'], 1)} USD per contract on average ({f(pk['mean_pickoff_loss_volpts'], 2)} vol points).\n")
        table(["move", "pairs", "median latency (s)", "stale after 5 s", "mean loss (USD / contract)", "move beyond half-spread"], [[b, v["n"], f(v["median_latency_s"], 1), pct(v["share_stale_5s"]), f(v["mean_loss_usd"], 1), pct(v["share_exceeds_half_spread"])] for b, v in pk.get("by_bucket", {}).items()])
    sd = mi.get("spread_depth", [])
    if sd:
        table(["tenor", "moneyness", "instruments", "spread (vol pts)", "spread (% of mid)", "bid size", "ask size", "two-sided"], [[r["tenor"], r["moneyness"], r["instruments"], f(r["spread_volpts"], 1), f(r["rel_spread_pct"], 1), f(r["bid_size"], 1), f(r["ask_size"], 1), pct(r["two_sided_share"], 0)] for r in sd])
    bl = mi.get("blocks", {})
    if bl:
        P(f"Block trades in the history: {pct(bl['block_share_of_trades'])} of prints and {pct(bl['block_share_of_contracts'])} of contracts. Against Deribit's mark at the print, block prints sit a median {f(bl['block']['median_abs_diff_pct'], 1)} % from the mark in price ({f(bl['block']['median_abs_diff_volpts'], 2)} vol points) against {f(bl['screen']['median_abs_diff_pct'], 1)} % ({f(bl['screen']['median_abs_diff_volpts'], 2)} vol points) for screen prints; the aggressor's median cost against the mark is {f(bl['block']['aggressor_cost_pct_median'], 2)} % on blocks and {f(bl['screen']['aggressor_cost_pct_median'], 2)} % on the screen.\n")
        table(["size (contracts)", "block prints", "block |diff| (vol pts)", "block aggressor cost (%)", "screen prints", "screen |diff| (vol pts)", "screen aggressor cost (%)"], [[b, v["block"]["trades"], f(v["block"]["median_abs_diff_volpts"], 2), f(v["block"]["aggressor_cost_pct_median"], 2), v["screen"]["trades"], f(v["screen"]["median_abs_diff_volpts"], 2), f(v["screen"]["aggressor_cost_pct_median"], 2)] for b, v in bl.get("by_size", {}).items()])

rq = run.get("rfq", {})
if rq:
    P("## RFQ pricer: the standard structures off the latest surface\n")
    P(f"Index {f(rq.get('index'), 0)}, expiries {rq.get('expiries_days')} days, size 10 contracts, package factor 0.6 for two legs and 0.8 for three.\n")
    for k, v in rq.items():
        if isinstance(v, dict) and "quote" in v:
            P(f"- **{k}**: {v['quote']}")
    P()

P(f"Runtime {run.get('seconds', 0) / 60:.0f} minutes.\n")
with open(os.path.join(R, "summary.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out))
print("wrote", os.path.join(R, "summary.md"))
